### ISSUE TITLE
attack in bank

### ISSUE THREAD

**Issue by camelot317** [7winds/Project-Aeolus#1]
Hello,

If something attack you in bank like in my image ,dont leave you to walk anymore  until u logout
http://prntscr.com/876xdi
oh and one banker is aggresive:))
I changed that banker id but its still aggresive i think is something with that bank region
::npc command dont work

**Comment by 7winds** [comment]
npc command doesn't work because that's using the old cfg crap.

**Comment by camelot317** [comment]
Yes , it work tnx.
Bugs:
-One banker from edge bank is aggresive and isnt from npcdef , npc id 494
-Few new icons on magic tab left  http://prntscr.com/88e7br  http://prntscr.com/88e7rg
-Wilderness ditch map/texture is bugged http://prntscr.com/88e83w (maybe u can remove it complete will be much better.)
-Server  crash  if you try to attack any monster without weapon

Aug 24, 2015 7:03:52 PM [core.game.model.entity.player.Player]  login
INFO: [REGISTERED]: Mod wind
java.lang.ArrayIndexOutOfBoundsException: -1
	at core.game.model.item.ItemAssistant.getItemId(ItemAssistant.java:26)
	at core.game.model.entity.player.combat.PlayerVsMob.attackNpc(PlayerVsMob.java:585)
	at core.game.content.CombatAssistant.attackNpc(CombatAssistant.java:130)
	at core.net.packets.incoming.ClickNPC.processPacket(ClickNPC.java:131)
	at core.net.packets.PacketHandler.processPacket(PacketHandler.java:145)
	at core.game.model.entity.player.Player.processQueuedPackets(Player.java:754)
	at core.game.model.entity.player.PlayerHandler.process(PlayerHandler.java:127)
	at core.Server$1.execute(Server.java:179)
	at core.game.event.task.Task2.tick(Task2.java:103)
	at core.game.event.task.TaskScheduler.run(TaskScheduler.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.ArrayIndexOutOfBoundsException: -1
	at core.game.model.item.ItemAssistant.getItemId(ItemAssistant.java:26)
	at core.game.model.entity.player.combat.PlayerVsMob.attackNpc(PlayerVsMob.java:585)
	at core.game.content.CombatAssistant.attackNpc(CombatAssistant.java:130)
	at core.game.model.entity.player.Player.process(Player.java:2298)
	at core.game.model.entity.player.PlayerHandler.process(PlayerHandler.java:128)
	at core.Server$1.execute(Server.java:179)
	at core.game.event.task.Task2.tick(Task2.java:103)
	at core.game.event.task.TaskScheduler.run(TaskScheduler.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.ArrayIndexOutOfBoundsException: -1
	at core.game.model.item.ItemAssistant.getItemId(ItemAssistant.java:26)
	at core.game.model.entity.player.combat.PlayerVsMob.attackNpc(PlayerVsMob.java:585)
	at core.game.content.CombatAssistant.attackNpc(CombatAssistant.java:130)
	at core.game.model.entity.player.Player.process(Player.java:2298)
	at core.game.model.entity.player.PlayerHandler.process(PlayerHandler.java:128)
	at core.Server$1.execute(Server.java:179)
	at core.game.event.task.Task2.tick(Task2.java:103)
	at core.game.event.task.TaskScheduler.run(TaskScheduler.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

I will try to post all bugs if you need them.

**Comment by lare96** [comment]
Has this been fixed?

**Comment by camelot317** [comment]
nop

**Comment by 7winds** [comment]
Fixed attacking without a weapon crash, also fixed walkable interfaces today.

**Comment by 7winds** [comment]
Fixed the randomly aggresive npc issue.
